from typing import Optional, Protocol


class DedicatedNicRepoInterface(Protocol):
    """Abstract interface for dedicated NIC configuration persistence."""

    def save_config(self, container_name: str, config: dict) -> None: ...
    def load_config(self, container_name: str) -> Optional[dict]: ...
    def load_all_configs(self) -> dict: ...
    def delete_config(self, container_name: str) -> None: ...
    def get_container_for_nic(self, interface_name: str) -> Optional[str]: ...
